name: nutrition_effort_proto
description: Prototype Nutrition â†” Effort
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  http: ^1.2.0
  xml: ^6.5.0
  file_picker: ^8.0.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: any


flutter:
  uses-material-design: true
